services:
  sudoku:
    build:
      context: https://git.local.nirbslab.com/nirb/sudoku.git
    container_name: sudoku
    restart: unless-stopped
    # ports:
    #   - "8080:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sudoku.rule=Host(`sudoku.local.nirbslab.com`)"
      - "traefik.http.routers.sudoku.entrypoints=websecure"
      - "traefik.http.routers.sudoku.tls=true"
      - "traefik.http.routers.sudoku.tls.certresolver=letsencrypt"
      - "traefik.http.services.sudoku.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
