#!/usr/bin/env node
// Produces a reviewable proposal. Applying it requires an explicit --apply.
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { PUZZLES } from '../puzzle-bank.js';
import { SudokuSolver } from '../solver.js';
import { puzzleId } from '../puzzle-id.js';
import { RATING_POLICY, RATING_FAMILIES, difficultyFor, ratingKey, compareRatingKeys } from '../rating-policy.js';
const root = fileURLToPath(new URL('../', import.meta.url));
const hash = data => createHash('sha256').update(data).digest('hex');
try {
    const args = {};
    for (const arg of process.argv.slice(2)) {
        const [key, ...parts] = arg.split('=');
        if (!['--assessment', '--out', '--apply'].includes(key) || key in args || (key === '--apply' ? parts.length : !parts.join('='))) throw new Error('Invalid arguments');
        args[key] = key === '--apply' ? true : parts.join('=');
    }
    if (!args['--assessment'] || !args['--out']) throw new Error('Use --assessment=JSON --out=NEW_DIRECTORY [--apply]');
    const out = path.resolve(args['--out']);
    if (fs.existsSync(out)) throw new Error('Output directory already exists');
    const source = fs.readFileSync(args['--assessment']);
    const assessment = JSON.parse(source);
    if (assessment.policy?.version !== 'human-v4.0' || assessment.policy?.profile !== 'maintenance') throw new Error('Wrong assessment policy');
    for (const [file, expected] of Object.entries(assessment.provenance?.sourceHashes || {})) {
        if (path.isAbsolute(file) || file.split('/').includes('..') || hash(fs.readFileSync(path.join(root, file))) !== expected) throw new Error('Assessment source mismatch');
    }
    if (!assessment.provenance?.sourceHashes?.['enhanced-assessment.js']) throw new Error('Missing assessment provenance');
    const current = Object.values(PUZZLES).flat().map(p => p.puzzle);
    const records = assessment.records;
    if (!Array.isArray(records) || records.length !== current.length || new Set(records.map(r => r.puzzle)).size !== current.length || records.some(r => !current.includes(r.puzzle))) throw new Error('Assessment must cover the exact complete bank');
    const rows = records.map(r => ({ id: puzzleId(r.puzzle), puzzle: r.puzzle, difficulty: difficultyFor(r.human), key: ratingKey(r.human), clues: r.human.clues }));
    if (new Set(rows.map(r => r.id)).size !== rows.length) throw new Error('Puzzle identity collision');
    for (const r of rows) if (SudokuSolver.countSolutions(r.puzzle, 2) !== 1) throw new Error('Puzzle is not unique');
    rows.sort((a, b) => compareRatingKeys(a.key, b.key) || (a.id < b.id ? -1 : 1));
    const tiers = Object.fromEntries(Object.keys(PUZZLES).map(d => [d, rows.filter(r => r.difficulty === d)]));
    const sizes = Object.fromEntries(Object.entries(tiers).map(([d, a]) => [d, a.length]));
    if (Object.values(sizes).some(n => !n)) throw new Error('Empty tier');
    const bank = `// ${rows.length.toLocaleString('en-US')} puzzles, ordered by ${RATING_POLICY}. Generated by scripts/reclassify-bank.js.\n// No solutions. Content identities are independent of difficulty and level.\nimport { puzzleId } from './puzzle-id.js';\nexport const PUZZLE_STRINGS = {\n` +
        Object.entries(tiers).map(([d, a]) => `    ${d}: [\n${a.map(r => `        '${r.puzzle}',`).join('\n')}\n    ],`).join('\n') +
        `\n};\nexport const PUZZLES = Object.fromEntries(Object.entries(PUZZLE_STRINGS).map(([d, list]) => [d, list.map(puzzle => ({ id: puzzleId(puzzle), puzzle }))]));\nexport const ALL_PUZZLES = Object.entries(PUZZLES).flatMap(([difficulty, list]) => list.map((p, index) => ({ ...p, difficulty, level: index + 1 })));\n`;
    const metadata = { version: 2, policy: RATING_POLICY, sizes };
    const ranks = { policy: RATING_POLICY, policySourceSha256: hash(fs.readFileSync(path.join(root, 'rating-policy.js'))), assessmentSha256: hash(source), boardSetSha256: hash([...current].sort().join('\n')),
        tiers: Object.fromEntries(Object.entries(tiers).map(([d, a]) => [d, a.map(r => [r.id, ...r.key])])) };
    const ids = Object.fromEntries(Object.entries(tiers).map(([d, a]) => [d, a.map(r => r.id)]));
    const variants = records.flatMap(r => (r.transformations || []).map(t => ({ original: r.human.family, originalId: puzzleId(r.puzzle), ...t })));
    const changed = variants.filter(t => t.status !== 'solved' || t.family !== t.original);
    if (variants.some(t => t.status !== 'solved' || !RATING_FAMILIES.includes(t.family))) throw new Error('Review unfinished transformed assessments before applying');
    if (variants.some(t => RATING_FAMILIES.indexOf(t.family) < RATING_FAMILIES.indexOf(t.original))) throw new Error('Review simpler transformed paths before applying');
    const range = values => { const a = values.sort((x, y) => x - y); return [a[0], a[Math.floor(a.length / 2)], a[Math.ceil(a.length * .9) - 1], a.at(-1)].join(' / '); };
    const report = ['# Bank revision 2 — human-technique ladder', '', `Policy: ${RATING_POLICY}. All ${rows.length} original boards retained and uniquely solvable.`, '',
        '| Tier | Puzzles | Verified path families |', '|---|---:|---|',
        ...Object.entries(tiers).map(([d, a]) => `| ${d} | ${a.length} | ${[...new Set(a.map(r => RATING_FAMILIES[r.key[0]]))].join(', ')} |`), '',
        '## Measurements', '', 'Ranges are minimum / upper median / nearest-rank P90 / maximum. Clue count is descriptive, never a ranking input.', '',
        '| Tier | Clues | Elimination steps | Largest proof nodes | Total steps |', '|---|---|---|---|---|',
        ...Object.entries(tiers).map(([d, a]) => `| ${d} | ${range(a.map(r => r.clues))} | ${range(a.map(r => r.key[5]))} | ${range(a.map(r => r.key[3]))} | ${range(a.map(r => r.key[7]))} |`), '',
        '## Transformation review', '', `Transformation assessments: ${variants.length}; all solved. Changed observed family: ${changed.length}.`, '',
        ...changed.map(t => `- ${t.originalId}: original ${t.original}, transformed ${t.family}. Keep the simpler verified original path; this records an order-sensitive search result, not a change in the mathematical puzzle.`), '',
        'These checks reverse digits, transpose the board and swap the first two rows. They cover the entire bank but do not enumerate every legal Sudoku symmetry. Step counts and selected paths can differ; no claim of complete transformation invariance is made.', '',
        '## Ordering and boundaries', '',
        'Order: family, named technique within that family, deepest proof, largest proof, largest branch count, elimination steps, candidate eliminations, total steps, opening eliminations, content identity. Chain shapes share one named band; their proof complexity determines order.', '',
        'The exact named-pattern sequence is in rating-policy.js. Every level and its comparison key are recorded in bank-ranking.json; these maintenance files are not downloaded by the app.', '',
        ...Object.entries(tiers).map(([d, a]) => `- ${d}: level 1 ${a[0].id}; level ${a.length} ${a.at(-1).id}.`), '',
        'The policy orders observed reasoning paths. It does not prove a globally simplest path or a universal human difficulty order. SE is an independent comparison, not the source of these labels.', '',
        '## Release behavior', '', 'This is an intentional bank revision: no compatibility mapping for old numbered links, saved games, played lists or score records. Settings and calendar streaks are retained. Old storage is left untouched under its previous keys; old backups cannot be restored into this bank. New shared bank links use stable board identities.', '',
        'Expert and Nightmare are the first candidates for targeted expansion in v1.2.0. Smaller counts are not a defect to fix by adding symmetry duplicates or unresolved puzzles. No new puzzles or board sizes are included in v1.1.0.', '',
        '## Repeat the assessment', '', 'Run from the repository root, using new output paths:', '', '```bash',
        'node scripts/assess-v4.js --all --transforms --out=e2e-results/new-rating.json',
        'node scripts/reclassify-bank.js --assessment=e2e-results/new-rating.json --out=e2e-results/new-proposal',
        '```', '',
        'Review the generated files before using --apply with another fresh output directory. The tool refuses incomplete/stale inputs, unresolved variants or a transformed path with a simpler family that has not been reviewed. The same assessor accepts --puzzle=GRID and --file=LINES for imported and newly generated boards.', '',
        'Earlier reports retain the previous level references. Re-running them on this bank produces the same puzzles grouped under their new labels; their original result files are not overwritten.', '',
        `Assessment SHA-256: ${ranks.assessmentSha256}`, `Board-set SHA-256: ${ranks.boardSetSha256}`, ''].join('\n');
    fs.mkdirSync(out, { recursive: true });
    for (const [file, data] of Object.entries({ 'puzzle-bank.js': bank, 'bank-meta.json': JSON.stringify(metadata, null, 2) + '\n',
        'bank-ids.json': JSON.stringify(ids) + '\n', 'bank-ranking.json': JSON.stringify(ranks) + '\n', 'proposal.md': report })) fs.writeFileSync(path.join(out, file), data, { flag: 'wx' });
    if (args['--apply']) {
        fs.copyFileSync(path.join(out, 'puzzle-bank.js'), path.join(root, 'puzzle-bank.js'));
        for (const file of ['bank-meta.json', 'bank-ids.json']) fs.copyFileSync(path.join(out, file), path.join(root, 'leaderboard-api', file));
        fs.copyFileSync(path.join(out, 'bank-ranking.json'), path.join(root, 'docs', 'bank-ranking.json'));
        fs.copyFileSync(path.join(out, 'proposal.md'), path.join(root, 'docs', 'bank-revision-2.md'));
    }
    console.log(report);
} catch (e) { console.error(e.message); process.exitCode = 1; }
